### ISSUE TITLE
Apply a custom stylesheet/theme

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/asciidoctor-pdf.js#60]
We should introduce an attribute named `pdf-style` (or maybe use the `stylesheet` and `stylesdir` attributes ?) to provide a custom stylesheet.

I think the default style should be named `default.css` and we should support the `@import` directive. The idea is to be able to extend the default style:

```css
@import 'default.css';

.role.red {
  color: #ff0000;
}
```

To avoid path resolution issues, we will probably need to replace the directive with the actual content.
`default.css` will be a reserved name.

It should also be possible to use `@import` to include stylesheets:

**color.css**
```css
:root {
  --main-color: #2b2d2f;
}
```

```css
@import 'default.css';
@import 'color.css';

.paragraph {
  color: var(--main-color);
}

.title {
  color: var(--main-color);
}
```
