### ISSUE TITLE
Inline styles are ignored by Paged.js

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/asciidoctor-pdf.js#75]
The following does not create a page break when using Paged.js:

```html
<div style="page-break-after: always;"></div>
```

We should also define a CSS class with an associated rule:

```html
<div class="page-break" style="page-break-after: always;"></div>
```

```css
.page-break {
  page-break-after: always;
}
```
